// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/data/:dataId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data/[dataId]').default>>>>
    }
    '/api/files/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/[...]').default>>>>
    }
    '/api/proxy/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/[...path]').default>>>>
    }
    '/api/shop/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shop/[...]').default>>>>
    }
    '/api/teams/:teamId/members/:memberId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[teamId]/members/[memberId]').default>>>>
    }
    '/api/users/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]').default>>>>
    }
    '/api/widgets/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/widgets/[...]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}